app:
  jwt:
    secret: doSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlFdoSCf7QzUN8XxRr9eTGaLAOPOb4yWq1NMFDUV5MhH39MbDZJbaLarAie42MleAlF
    refresh:
      expirationMinutes: 360
    access:
      expirationMinutes: 60

defaultTenant: tenant_1
tenantPropertiesPath: application/src/main/resources/tenants
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.iotiq.dev/realms/kimono
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: info
opentelemetry:
  enabled: false

#logging:
#  level:
#    com:
#      iotiq:
#        abakus:
#          config:
#            RequestLogger: debug
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace
