package com.iotiq.application.domain.enums;

public enum Material {
    COTTON,
    LEATHER,
    FAUX_LEATHER,
    COTTON_75_PERCENT,
    COTTON_50_PERCENT,
    HYBRID_STANDARD_FILAMENT_FABRIC,
    POLYESTER,
    VISCOSE,
    SILK,
    ELASTANE,
    MODAL,
    LYOCELL,
    PROTEIN,
    CHITOSAN,
    BROWN_ALGAE_EXTRACT,
    NANO_SILVER,
    SILK_FIBROIN,
    POLYTETRAFLUOROETHYLENE,
    ZINC_OXIDE,
    NEMOLIZUMAB,
    CORTIOSONE
}
