package com.iotiq.application.domain.enums;

public enum Skill {
    YARN_SUPPLY,
    WOVEN_FABRIC,
    FINISHING,
    PROTOTYPE,
    PRODUCT_PARAMETER_MODELING,
    MODELING_SUPPORT,
    CO_DESIGN,
    PATTERN_CREATION,
    CUTTING,
    ASSEMBLY,
    ACTIVE_SUBSTANCE_PLACEMENT,
    QUALITY_CONTROL,
    B2C,
    RECYCLING
}
